version: "3.8"

services:
  xds:
    image: rueian/zenvoy-xds:latest
    build:
      context: .
      target: xds
    ports:
      - 18000:18000
    depends_on:
      - proxy
  proxy:
    image: rueian/zenvoy-proxy:latest
    build:
      context: .
      target: proxy
    cap_add:
      - NET_ADMIN
    ports:
      - 20000:20000
  echo:
    image: rueian/zenvoy-echo:latest
    build:
      context: .
      target: echo
    ports:
      - 8080:8080
  envoy:
    image: envoyproxy/envoy:v1.16.0
    volumes:
      - ./hack/envoy:/etc/envoy
    ports:
      - 10000:10000
      - 10001:10001
    depends_on:
      - xds
