version: "3.8"

services:
  zenvoy-xds:
    image: rueian/zenvoy-xds:latest
    build:
      context: .
      target: xds
    environment:
      PROXY_ADDR: proxy
    ports:
      - 18000:18000
    depends_on:
      - zenvoy-proxy
  zenvoy-proxy:
    image: rueian/zenvoy-proxy:latest
    build:
      context: .
      target: proxy
    environment:
      PROXY_ADDR:
    cap_add:
      - NET_ADMIN
    ports:
      - 20000:20000
  zenvoy-echo:
    image: rueian/zenvoy-echo:latest
    build:
      context: .
      target: echo
    ports:
      - 8080:8080
  envoy:
    image: envoyproxy/envoy:v1.16.0
    volumes:
      - ./hack/envoy:/etc/envoy
    ports:
      - 10000:10000
      - 10001:10001
    depends_on:
      - zenvoy-xds
